# Use postgres/example user/password credentials
version: '3.1'

services:
# https://hub.docker.com/_/postgres
# https://github.com/cookiecutter/cookiecutter-django
# https://cookiecutter-django.readthedocs.io/en/latest/developing-locally-docker.html

  backend:
    #    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:

    image: postgres:15
    container_name: django-tfg-DB
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - djangotfg_postgres_data:/var/lib/postgresql/data
      - djangotfg_data_backups:/backups
    ports:
      - 5432:5432

volumes:
  djangotfg_postgres_data:
  djangotfg_data_backups:

