# Use postgres/example user/password credentials
version: '3.1'

services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    volumes:
      - .:/app
      - profile_pics:/app/media/profile_pics  # Añadir esta línea
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: django-tfg-DB
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - djangotfg_postgres_data:/var/lib/postgresql/data
      - djangotfg_data_backups:/backups
    ports:
      - 5432:5432

volumes:
  djangotfg_postgres_data:
  djangotfg_data_backups:
  profile_pics: