# Generated by Django 5.0.3 on 2024-05-03 15:51

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('expiration', models.DateField()),
                ('cvv', models.IntegerField(validators=[main.models.validate_card])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.client')),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'unique_together': {('type', 'owner')},
            },
        ),
    ]
