# Generated by Django 5.0.3 on 2024-06-07 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('geo', '0018_voyage_age_group'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.voyage')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.voyagethread'),
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
