# Generated by Django 5.0.3 on 2024-05-03 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Continents',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code_iso2', models.CharField(max_length=2, unique=True)),
                ('code_iso3', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('num_code', models.IntegerField()),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('itinerary', models.TextField(default='Itinerario predeterminado.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('maximun_travellers', models.IntegerField()),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo.country')),
            ],
            options={
                'verbose_name_plural': 'Voyages',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('voyage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geo.voyage')),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
