# Generated by Django 5.0.3 on 2024-03-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code_iso2', models.CharField(max_length=2, null=True, unique=True)),
                ('code_iso3', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code_iso2', models.CharField(max_length=2, null=True, unique=True)),
                ('code_iso3', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('num_code', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.city')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.country')),
            ],
            options={
                'verbose_name_plural': 'Continents',
            },
        ),
    ]
