# Generated by Django 5.0.3 on 2024-04-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
