# Generated by Django 5.0.3 on 2024-03-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='code_iso3',
        ),
        migrations.AlterField(
            model_name='city',
            name='code_iso2',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code_iso2',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
