# Generated by Django 5.0.3 on 2024-05-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='maximun_travellers',
            new_name='maximun_travelers',
        ),
    ]
