# Generated by Django 5.0.3 on 2024-04-02 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_remove_city_code_iso3_alter_city_code_iso2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.continent'),
        ),
    ]
