# Generated by Django 5.0.3 on 2024-05-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_rename_maximun_travellers_voyage_maximun_travelers'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='description',
            field=models.TextField(default='Resumen'),
        ),
    ]
