# Generated by Django 5.0.3 on 2024-05-10 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_voyage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='date',
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
