# Generated by Django 5.0.3 on 2024-05-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_alter_voyage_date_end_alter_voyage_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='country',
        ),
        migrations.AddField(
            model_name='voyage',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geo.city'),
        ),
    ]
