# Generated by Django 5.0.3 on 2024-05-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_remove_voyage_country_voyage_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='maximun_travelers',
            new_name='maximum_travelers',
        ),
    ]
