# Generated by Django 5.0.3 on 2024-05-18 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_rename_maximun_travelers_voyage_maximum_travelers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('second_surname', models.CharField(max_length=32)),
                ('email', models.CharField()),
                ('birth_date', models.DateField()),
                ('telephone', models.CharField(max_length=16)),
                ('dni', models.CharField(max_length=16, null=True)),
                ('passport', models.CharField(max_length=16, null=True)),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.city')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.purchase')),
            ],
        ),
    ]
