# Generated by Django 5.0.3 on 2024-05-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_purchase_amount_alter_purchase_date'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.card'),
        ),
    ]
