# Generated by Django 5.0.3 on 2024-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_voyage_active_travelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyager',
            name='second_surname',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
