# Generated by Django 5.0.3 on 2024-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0015_alter_voyager_second_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyager',
            name='dni',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='voyager',
            name='passport',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
