# Generated by Django 5.0.3 on 2024-05-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0016_alter_voyager_dni_alter_voyager_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='active_travelers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
